### ISSUE TITLE
I am unable to login to ctrader account using my credentials

### ISSUE THREAD

**Issue by akbaralifreedom123** [Reiryoku-Technologies/Mida#122]
I am unable to get my ctrader user account getting through login using MIDA API, I tried a couple of such accounts but it's still not getting me through it. Its working fine for last two months, but suddenly stopped working yesterday May 25, 2023. 

const clientId = '****';
const clientSecret = '****';
const accessToken = '****';
const accountId = '****';

   const account = await login("cTrader", {
            clientId: clientId,
            clientSecret: clientSecret,
            accessToken: accessToken,
            accountId: accountId,
        });

Here is the version I am using.
  "devDependencies": {
    "@reiryoku/mida": "^2023.1.2",

And here is the error.

Error
    at CTraderApplication.loginTradingAccount (D:\code\repos\Freedom.Trading\Freedom.Trading\Freedom.Trading.NextGen\Freedom.Trading.Mida\node_modules\@reiryoku\mida\build\src\platforms\ctrader\CTraderApplication.js:69:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CTrader.login (D:\code\repos\Freedom.Trading\Freedom.Trading\Freedom.Trading.NextGen\Freedom.Trading.Mida\node_modules\@reiryoku\mida\build\src\platforms\ctrader\CTrader.js:34:32)

----

Edited by @Vasile-Peste to censor credentials

**Comment by Vasile-Peste** [comment]
Hello, right now it works fine on our side, maybe cTrader had issues in that period?

**Comment by akbaralifreedom123** [comment]
> Hello, right now it works fine on our side, maybe cTrader had issues in that period? Can you try again and let us know?
> 
> Thank you!

@Vasile-Peste Yes, I suspect it rejections from Ctrader, it persisted for over 20 hours, and then got resolved automatically. 
Thanks,
Akbar
