### ISSUE TITLE
ERRO EXE FUNCTION MIDA.LOGIN

### ISSUE THREAD

**Issue by eritondev-stack** [Reiryoku-Technologies/Mida#20]
Hello guys, I have error when try login.

PS C:\Users\es04707\Documents\ctrader> node index.js
C:\Users\es04707\Documents\ctrader\node_modules\@reiryoku\mida\build\src\core\Mida.js:18
        const pluginId = plugin?.id;
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\es04707\Documents\ctrader\node_modules\@reiryoku\mida\build\entry\node\main.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
PS C:\Users\es04707\Documents\ctrader> 

Can you help me?

**Comment by Vasile-Peste** [comment]
Hi, could you please provide more details about your environment? I think you are trying to use Mida in a browser right? Are you using React or Vue.js? In that case you have to use babel and some browserify on some modules. I agree that a guide on using Mida on browsers is necessary, let me know, thanks!

**Comment by eritondev-stack** [comment]
Thanks for helping, I'm using nodejs in backend.  I need use browser?

**Comment by Vasile-Peste** [comment]
> Thanks for helping, I'm using nodejs in backend. I need use browser?

No, you don't need to use browser. This means you have to update your Node.js version, I recommend using at least Node.js 16, you can use this package to update and switch bewteen Node.js versions => https://www.npmjs.com/package/n

**Comment by eritondev-stack** [comment]
Thanks for sharing, I fixed my error...

Bless you!!!
