### ISSUE TITLE
Mida login on AWS lambda 

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida#72]
Hi, I've successfully managed to run Mida login on my computer and different VMs.

Nevertheless, trying it on AWS Lambda I get this error:
`ERROR	TypeError: Cannot read properties of null (reading 'build')
    at CTraderProtobufReader.build (/var/task/index.js:14681:17)
    at new CTraderConnection (/var/task/index.js:15028:78)
    at new CTraderApplication (/var/task/index.js:17078:74)
    at Function.<anonymous> (/var/task/index.js:17163:171)
    at Generator. next (<anonymous>)
    at /var/task/index.js:17031:71
    at new Promise (<anonymous>)
    at __awaiter (/var/task/index.js:17013:14)
    at Function.create (/var/task/index.js:17162:16)
    at CTrader.<anonymous> (/var/task/index.js:17222:84)`
    
Is there any installation guide for AWS Lambda?
Or at least is it possible to obtain a more understandable error?

**Comment by desoss** [comment]
Hey @Vasile-Peste, thanks for your answer. It makes totally sense.
Configuring a file system for the AWS Lambda it's possible. 

Nevertheless, it would cost slightly more and it'll slow down the code execution.
(Because also a VPC has to be configured)

Nevertheless, it's possible to read/write from a local disk in a Lambda function without configuring a file system, but writing is limited to the `/tmp` directory. 

Would it be possible to make configurable the root directory in which the .proto files are stored?

**Comment by desoss** [comment]
I've inspected the code you wrote and I've solved the problem described above.
There are no write permissions needed. So no custom file system is needed for the AWS Lambda function.

The problem that I had was related to the fact that I was bundling my Lambda function, compiling it into a single file.
Simply excluding all the Mida dependencies from the produced bundle did the job!

As a suggestion, I would raise an exception in the `load()` function that you wrote if the .proto files are not correctly loaded.

**Comment by desoss** [comment]
@JoeGuest 

```
 new NodejsFunction(this, '....', {
    ...            
    bundling: {
          ....       
          minify: false,
          nodeModules: ['@reiryoku/mida-ctrader', '@reiryoku/mida'],
     }
}
```

**Comment by desoss** [comment]
Hi guys,
some updates, 
The minify:false is not needed and since mida version 3.0.1 every plugin has been unified hence the code that I posted above would become:
` new NodejsFunction(this, '....', {
    ...            
    bundling: {
          ....       
          minify: false,
          nodeModules: ['@reiryoku/mida-ctrader', '@reiryoku/mida'],
     }
}`

Furthermore, I'm digging into this problem a little bit more and it seems that the problem is related to the protobufjs version that we're using, that's why I've opened also this [issue](https://github.com/Reiryoku-Technologies/cTrader-Layer/issues/11).
